name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Build output
        id: build
        run: |
          echo "::set-output name=OUTPUT::$( make html )"

      - name: Show output
        run: echo ${{ steps.build.outputs.OUTPUT }}
